import { PlayerCard } from '../../components'

const AboutUs = () => {
  return (
    <div className='about page'>
      <h1 className='about__heading'>SÖNDAGSGÄNGET</h1>
      <div className='about__players'>
        <ul className='about__players-list'>
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/JJ.jpg?etag=%2297f2-5a8b28a3%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=142%2B159&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/LJ.jpg?etag=%224f9e-5a8b28a3%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=139%2B161&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/SH.jpg?etag=%22b8c7-5a8b28a3%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=146%2B152&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/Hossa.jpg?etag=%22ba1f-5aa6c789%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=103%2B207&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/GB.jpg?etag=%22a07c-5a8b28a3%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=123%2B151&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/CP.jpg?etag=%2295bf-5a8b28a3%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=139%2B163&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/TC.jpg?etag=%2237c7e-5a8b28a4%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=147%2B160&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/RP.jpg?etag=%2275ec-5a8b28db%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=144%2B158&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/Lars%20S.jpg?etag=%224640-5a8b28a3%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=130%2B166&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/BL.jpg?etag=%223862-5a8b28a3%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=136%2B158&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/DG.jpg?etag=%229b2a-5eb99fe0%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=172%2B200&extract=25%2B14%2B136%2B160&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/AL.jpg?etag=%229b52-5eb99fdf%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=158%2B200&extract=0%2B0%2B134%2B160&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/AH.jpg?etag=%22743b-5eb99fdf%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=190%2B211&extract=35%2B0%2B135%2B160&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/JS.jpg?etag=%22a9ee-5eb99fe0%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=181%2B200&extract=27%2B24%2B135%2B160&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/JTF.jpg?etag=%226d3c-5a8b28a3%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=136%2B142&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/Peter%20N.jpg?etag=%223b55-5aa6c7eb%22&sourceContentType=image%2Fjpeg'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/MA.jpg?etag=%226feb-5eb99fe1%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=125%2B160&quality=85'
            }
            info={'Proffs'}
          />
          <PlayerCard
            img={
              'https://www.golfers.nu/____impro/1/Spelare/LG.jpg?etag=%22a7f1-5eb99fe1%22&sourceContentType=image%2Fjpeg&ignoreAspectRatio&resize=180%2B200&extract=28%2B0%2B126%2B160&quality=85'
            }
            info={'Proffs'}
          />
        </ul>
      </div>
    </div>
  )
}

export default AboutUs
